name: ML CI CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  ML-CI-Pipeline:
    runs-on: ubuntu-latest

    steps:
    # -------------------------
    # Checkout code
    # -------------------------
    - name: Checkout repository
      uses: actions/checkout@v4

    # -------------------------
    # Setup Python
    # -------------------------
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11.9"

    # -------------------------
    # Install dependencies
    # -------------------------
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # -------------------------
    # Linting
    # -------------------------
    - name: Run flake8 linting
      continue-on-error: true
      run: |
        flake8 app/ tests/ --max-line-length=100

    # -------------------------
    # Unit tests
    # -------------------------
    - name: Run unit 
      continue-on-error: true
      run: |
        pytest --junitxml=test-results.xml

    # -------------------------
    # Execute eda_preprocess.py
    # -------------------------
    - name: Run preprocess eda train evaluate
      continue-on-error: true
      run: |
        python src/eda_preprocess.py

    # -------------------------
    # Execute train_evaluate_model.py
    # -------------------------
    - name: Run train and evaluate
      continue-on-error: true
      run: |
        python src/train_evaluate_model.py

    # -------------------------
    # Set up Docker Buildx
    # -------------------------
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # -------------------------
    # Login to Docker Hub
    # -------------------------
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # -------------------------
    # Build and Push Image
    # -------------------------
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/bits_mtech_mlops_2:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/bits_mtech_mlops_2:${{ github.sha }}

  ML-CD-Pipeline:
    runs-on: ubuntu-latest
    needs: ML-CI-Pipeline

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 1. Authenticate to Google Cloud 
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      # 2. Set up GKE credentials
      - id: 'get-credentials'
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: 'autopilot-cluster-1'
          location: 'europe-central2' # or your cluster region/zone

      - name: Update Image and Deploy to Kubernetes 
        run: |
          # 1. Replace the placeholder 'IMAGE_TAG' with the actual GitHub SHA
          sed -i "s|IMAGE_NAME_TAG|${{ secrets.DOCKERHUB_USERNAME }}/bits_mtech_mlops_2:${{ github.sha }}|g" charts/deployment.yaml
          
          # 2. Apply the updated manifest immediately
          kubectl apply -f charts/ --namespace bits

  Smoke-Test:
    name: Smoke Test
    needs: ML-CD-Pipeline
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install curl & jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Health Check
        run: |
          echo "Checking /health endpoint..."
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://34.102.150.120/health)

          if [ "$STATUS" -ne 200 ]; then
            echo "Health check failed with status $STATUS"
            exit 1
          fi

          echo "Health check passed"

      - name: Predict API Test
        run: |
          echo "Testing /predict endpoint..."

          RESPONSE=$(curl -s -w "\n%{http_code}" \
            --request POST \
            --url http://34.102.150.120/predict \
            --header 'content-type: multipart/form-data' \
            --form file=@tests/data/51.jpg)

          BODY=$(echo "$RESPONSE" | head -n -1)
          STATUS=$(echo "$RESPONSE" | tail -n1)

          echo "Response body: $BODY"
          echo "Status code: $STATUS"

          if [ "$STATUS" -ne 200 ]; then
            echo "Predict endpoint failed"
            exit 1
          fi

          echo "Smoke test passed"

  Post-Deploy-Evalation-Test:
    name: Post Deploy Evalation Test
    needs: Smoke-Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # -------------------------
      # Install dependencies
      # -------------------------
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # -------------------------
      # Execute post_deploy_eval.py
      # -------------------------
      - name: Run post_deploy_eval script
        run: |
          python src/post_deploy_eval.py
